[package]
name = "texplo"
version = "0.14.0"
edition = "2024"

[dependencies]
crossterm = { path = "../TRUEOS-Blueprints/vendor/crossterm-0.29.0-trueos", default-features = false, features = ["events"] }

[target.'cfg(any(target_os = "trueos", target_os = "zkvm"))'.dependencies]
trueos = { path = "../TRUEOS-Blueprints/api", features = ["tokio-runtime"] }

[patch.crates-io]
mio = { path = "../TRUEOS-Blueprints/vendor/mio-1.2.0" }
rustix = { path = "../TRUEOS-Blueprints/vendor/rustix-1.1.4-trueos" }
signal-hook-mio = { path = "../TRUEOS-Blueprints/vendor/signal-hook-mio-0.2.5-trueos" }

[profile.dev]
codegen-units = 1         
debug = "full"            
lto = true                
opt-level = 3        
panic = "abort"           
split-debuginfo = "packed"
strip = "symbols"         
incremental = true        
